### ISSUE TITLE
Unknown column 'salt' in 'field list'

### ISSUE THREAD

**Issue by GuikiPT** [rupeshmohanty/chat-api#3]
When i register a new user, im insert all inputs, and press register
he go to register.php and say "Unknown column 'salt' in 'field list'"

How im resolve that?

**Comment by rupeshmohanty** [comment]
The database you created must not have some field named 'salt'.

**Comment by Mic-R** [comment]
> The database you created must not have some field named 'salt'.

How does that have to be configured?
